fix(urls): Fix urls
Brillionfi/simple-wallet-demo pull request #17
Opened 2024-07-25 09:51 UTC by Astrak

2024-07-25 14:07 UTC, santiago-ab requested changes
Easy fix required

2024-07-25 14:07 UTC, santiago-ab commented on src/lib/logOut.ts
> +  await fetch(`${BASE_URL}/users/logout`, {
this is an API request

2024-08-05 08:34 UTC, majid-allianceblock requested changes

2024-08-05 08:34 UTC, majid-allianceblock commented on package.json
> +    "dev": "next dev -p 3002",
please revert this and just change it in your local

2024-08-05 08:34 UTC, majid-allianceblock commented on src/hooks/auth/getAuthorizationUrlSdk.ts
> +  console.log(url);
remove it

2024-08-23 12:57 UTC, closed without merging